import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Book } from "./../interfaces/interfaces";
import SearchInput from "../components/SearchInput/SearchInput";
import HorizontalListBooks from "../components/HorizontalListBooks/HorizontalListBooks";

interface HomeProps {
	books: Book[];
}

const Home: NextPage<HomeProps> = ({ books }) => {
	return (
		<div>
			<Head>
				<title>Biblioteca IBCL</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="my-10" />
			<main className="ml-2">
				<div className="flex justify-center">
					<SearchInput />
				</div>
				<div>
					<HorizontalListBooks
						books={books}
						title="Mais Visualizados"
					/>
					<HorizontalListBooks books={books} title="Adolescentes" />
					<HorizontalListBooks
						books={books}
						title="Vida Espiritual"
					/>
				</div>
        <div className="flex justify-center my-5">
          <span className="font-bold underline" onClick={() => alert("Em Construção")}>Livros de A a Z</span>
        </div>
			</main>
		</div>
	);
};

export const getStaticProps: GetStaticProps = async (context) => {
	const books: Book[] = [
		{
			title: "Cristianismo puro e simples",
			imageUrl:
				"https://www.figma.com/file/DgsyfXrXmNEylzgDnIOyqX/image/8c42b2e37a4a0d3ef1ee2e77ba73dc4f1ac2357d?fuid=585490137042248560"
		},
		{
			title: "Ansiedade: Como enfrentar o mal do século",
			imageUrl:
				"https://s3-alpha-sig.figma.com/img/d244/ab3b/ed3ca3c93a42e47c8b31be5115b21425?Expires=1636934400&Signature=Zo3~fgem5rbh9p9fIbhg9i9CeJw0XSmUO91nMi9BOajkdDyn4PnFKcFD4ZmyhwlyqxX1GFiiGzPGcy0S8klTjGx7LoFB55SfMAtoEfqsKW4qVoUTHSUIYpvbrE302Q2eESeCw6OjrBf-iOqX89yiH6WqWZGmtLod7EY3Lfpq8a5SwvhKri9y37GmggXcaXfuh~mDZQQvUcQMiEvgOi-mIuz~UV5dpj0a8cZhmK0NV6W8KVSAXtuh6jfkrnLH0OZVcNh2PLNBGOEzhkIt~AODj-lX4eJGXg5j6N9eOduaXtVY02kVd2pUoZ7Tpsz~FcIOH57hgGY2~XpobHez-EebwQ__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA"
		},
		{
			title: "Este mundo tenebroso - Parte 2",
			imageUrl:
				"https://s3-alpha-sig.figma.com/img/83d1/3b02/dbc473b9d0c3ac168c5b7ff715e352b5?Expires=1636934400&Signature=bncYOwNl4bUwmnTszF7VkPKqOztr-lmGHbgRUvHaM-koRpDndjOmaTR~uu4foT8uWO7oaea~K4vpkhsbqGBWjaoVsiJDg7sbwO-kKR9ZTHAAMHfRGFpeecX2Mif0FGjtwDvOSVK4NwL6yted1mzyr~Z~bh0V3OL9M2JXji2U--hEH4FL5VGkOZaVrS2fl7xx9AdmmRQ0V30mmYUP37I6KjG2~ccAPYYLYrrq6A-4GcPiB5xg940uCwG-2MrIpEspEnH6XkxShExOGsRlr6FPYOursp0fodtk1QUvgqHHg4ruMkvs1hoFqfy96ibL0pFfYgFkJoBRTb2PEtn2TuzoMQ__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA"
		},
		{
			title: "Cartas de um diabo para seu advogado",
			imageUrl:
				"https://s3-alpha-sig.figma.com/img/fdb3/4f8e/1b7aaf5d48d9635e3c28c4558728106f?Expires=1636934400&Signature=VSh5wDE1UJPzmdUuQm-ciKE5O9XDqNV9jnKCBeGPAYjFsuZQmdo8rTlDKUheInHZ37YNpEsZF5eeH6jQtPFDdv-o7FAbSb2T45T8OXxZUryKaziMAPlGxnTMZdl-p0SbOSbsY5rp8HYrqsTb2zQci4QFthCoYZ-PZSUoSbyNv3OaYAgn7Dv~orwx9o0DHkC945H4Pos3gwiJg3zKn~3CoJeO62~ToZqxYeH20p7czjq99ju2pmsRV-ZrIc3OUDtvMP4Qp1kGPkkjzBOy9R0Bf3itkRSqhBnx0xI9zDaWEDUJ~3pdGvAeyiovIUbsL5-i60qRMAfjHadm80c4ebLY6g__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA"
		}
	];
	return {
		props: { books }
	};
};

export default Home;
