import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Book } from "./../interfaces/interfaces";
import SearchInput from "../components/SearchInput/SearchInput";
import HorizontalListBooks from "../components/HorizontalListBooks/HorizontalListBooks";
import { Books } from "../utils/Books.mock";

interface HomeProps {
	books: Book[];
}

const Home: NextPage<HomeProps> = ({ books }) => {
	return (
		<div>
			<Head>
				<title>Biblioteca IBCL</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="my-10" />
			<main className="ml-2">
				<div className="flex justify-center">
					<SearchInput />
				</div>
				<div>
					<HorizontalListBooks
						books={books}
						title="Mais Visualizados"
					/>
					<HorizontalListBooks books={books} title="Adolescentes" />
					<HorizontalListBooks
						books={books}
						title="Vida Espiritual"
					/>
				</div>
				<div className="flex justify-center my-5">
					<span
						className="font-bold underline"
						onClick={() => alert("Em Construção")}
					>
						Livros de A a Z
					</span>
				</div>
			</main>
		</div>
	);
};

export const getStaticProps: GetStaticProps = async (context) => {
	const books: Book[] = Books;
	return {
		props: { books }
	};
};

export default Home;
